### PR TITLE
Generating new test snapshots for `main`

### PR DESCRIPTION
**Pull request by NachoSoto**
Requested by local user for [main](https://github.com/RevenueCat/purchases-android/tree/main)

### CODE REVIEW

**Comment by NachoSoto** [comment]
This fixed some strings and regressed others. I believe we're both aware of why and a path towards making this better. Are you ok with this @tonidero?

**Review by tonidero — APPROVED** [review]
Yeah, I see the only ones affected are templates 4 and 5, whose test data doesn't have an spanish locale, so the changes actually make sense. There are still some strings in spanish for the hardcoded strings in the footer, but we probably need to see how to inject the locale before getting those strings. Planning to take a look at this today. In the meantime, I think this looks good.

**Comment by tonidero** [comment]
I think this can be closed in favor of #6 right @NachoSoto ?

**Comment by NachoSoto** [comment]
Yes thank you

**Pull request closed without merging**
